### ISSUE TITLE
Unable to run eval step

### ISSUE THREAD

**Issue by ziqizh** [Kim-Minseon/RoCL#1]
Hi, thank you for your awesome work! I tried to run the evaluation step but the program is unable to load the checkpoint. Do you have an idea why this is happening? Thank you!

```
~/RoCL/src$ ./total_process.sh test '../checkpoint/ckpt.t7roclRep_attack_ep_0.0314_alpha_0.007_min_val_0.0_max_val_1.0_max_iters_7_type_linf_randomstart_Truecontrastive_ResNet18_cifar-10_b256_nGPU2_l256_0_projector_epoch_900' rocl ResNet18 0.1 'cifar-10' 1
CUDA ./total_process.sh test ../checkpoint/ name model learning rate
train_type       : linear_eval
finetune         : False
epochwise        : False
ss               : False
trans            : False
clean            : True
adv_img          : False
lr               : 0.1
lr_multiplier    : 15.0
dataset          : cifar-10
load_checkpoint  : ../checkpoint/ckpt.t7roclRep_attack_ep_0.0314_alpha_0.007_min_val_0.0_max_val_1.0_max_iters_7_type_linf_randomstart_Truecontrastive_ResNet18_cifar-10_b256_nGPU2_l256_0_projector_epoch_900
model            : ResNet18
name             : rocl
seed             : 1
batch_size       : 1024
epoch            : 150
color_jitter_strength : 0.5
temperature      : 0.5
local_rank       : 0
ngpu             : 1
min              : 0.0
max              : 1.0
attack_type      : linf
epsilon          : 0.0314
alpha            : 0.007
k                : 10
random_start     : True
2
Using CUDA..
==> Preparing data..
Files already downloaded and verified
Files already downloaded and verified
==> Building model..
ResNet18 is loading ...
Traceback (most recent call last):
  File "linear_eval.py", line 300, in <module>
    model, linear, projector, loptim, attacker = load(args, 0)
  File "linear_eval.py", line 89, in load
    model.load_state_dict(new_state_dict)
  File "/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ResNet:
        Missing key(s) in state_dict: "conv1.weight", "bn1.weight", "bn1.bias", "bn1.running_mean", "bn1.running_var", "layer1.0.conv1.weight", "layer1.0.bn1.weight", "layer1.0.bn1.bias", "layer1.0.bn1.running_mean", "layer1.0.bn1.running_var", "layer1.0.conv2.weight", "layer1.0.bn2.weight", "layer1.0.bn2.bias", "layer1.0.bn2.running_mean", "layer1.0.bn2.running_var", "layer1.1.conv1.weight", "layer1.1.bn1.weight", "layer1.1.bn1.bias", "layer1.1.bn1.running_mean", "layer1.1.bn1.running_var", "layer1.1.conv2.weight", "layer1.1.bn2.weight", "layer1.1.bn2.bias", "layer1.1.bn2.running_mean", "layer1.1.bn2.running_var", "layer2.0.conv1.weight", "layer2.0.bn1.weight", "layer2.0.bn1.bias", "layer2.0.bn1.running_mean", "layer2.0.bn1.running_var", "layer2.0.conv2.weight", "layer2.0.bn2.weight", "layer2.0.bn2.bias", "layer2.0.bn2.running_mean", "layer2.0.bn2.running_var", "layer2.0.shortcut.0.weight", "layer2.0.shortcut.1.weight", "layer2.0.shortcut.1.bias", "layer2.0.shortcut.1.running_mean", "layer2.0.shortcut.1.running_var", "layer2.1.conv1.weight", "layer2.1.bn1.weight", "layer2.1.bn1.bias", "layer2.1.bn1.running_mean", "layer2.1.bn1.running_var", "layer2.1.conv2.weight", "layer2.1.bn2.weight", "layer2.1.bn2.bias", "layer2.1.bn2.running_mean", "layer2.1.bn2.running_var", "layer3.0.conv1.weight", "layer3.0.bn1.weight", "layer3.0.bn1.bias", "layer3.0.bn1.running_mean", "layer3.0.bn1.running_var", "layer3.0.conv2.weight", "layer3.0.bn2.weight", "layer3.0.bn2.bias", "layer3.0.bn2.running_mean", "layer3.0.bn2.running_var", "layer3.0.shortcut.0.weight", "layer3.0.shortcut.1.weight", "layer3.0.shortcut.1.bias", "layer3.0.shortcut.1.running_mean", "layer3.0.shortcut.1.running_var", "layer3.1.conv1.weight", "layer3.1.bn1.weight", "layer3.1.bn1.bias", "layer3.1.bn1.running_mean", "layer3.1.bn1.running_var", "layer3.1.conv2.weight", "layer3.1.bn2.weight", "layer3.1.bn2.bias", "layer3.1.bn2.running_mean", "layer3.1.bn2.running_var", "layer4.0.conv1.weight", "layer4.0.bn1.weight", "layer4.0.bn1.bias", "layer4.0.bn1.running_mean", "layer4.0.bn1.running_var", "layer4.0.conv2.weight", "layer4.0.bn2.weight", "layer4.0.bn2.bias", "layer4.0.bn2.running_mean", "layer4.0.bn2.running_var", "layer4.0.shortcut.0.weight", "layer4.0.shortcut.1.weight", "layer4.0.shortcut.1.bias", "layer4.0.shortcut.1.running_mean", "layer4.0.shortcut.1.running_var", "layer4.1.conv1.weight", "layer4.1.bn1.weight", "layer4.1.bn1.bias", "layer4.1.bn1.running_mean", "layer4.1.bn1.running_var", "layer4.1.conv2.weight", "layer4.1.bn2.weight", "layer4.1.bn2.bias", "layer4.1.bn2.running_mean", "layer4.1.bn2.running_var". 
        Unexpected key(s) in state_dict: "linear_1.weight", "linear_1.bias", "linear_2.weight", "linear_2.bias". 
```

**Comment by ziqizh** [comment]
Turned out I chose the checkpoint for projector.

**Comment by yqy2001** [comment]
@ziqizh Hi, have you solved this problem? I can't load the checkpoint too. I've tried all the checkpoints.
